# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from typing import Any, TypeVar

from pyarr._sync.common.backup import Backup
from pyarr._sync.common.blocklist import Blocklist
from pyarr._sync.common.calendar import Calendar
from pyarr._sync.common.command import Command
from pyarr._sync.common.download_client import DownloadClient
from pyarr._sync.common.history import History
from pyarr._sync.common.import_list import ImportList
from pyarr._sync.common.indexer import Indexer
from pyarr._sync.common.log import Log
from pyarr._sync.common.metadata import Metadata
from pyarr._sync.common.notification import Notification
from pyarr._sync.common.quality_definition import QualityDefinition
from pyarr._sync.common.quality_profile import QualityProfile
from pyarr._sync.common.queue import Queue
from pyarr._sync.common.remote_path_mapping import RemotePathMapping
from pyarr._sync.common.root_folder import RootFolder
from pyarr._sync.common.system import System
from pyarr._sync.common.tag import Tag
from pyarr._sync.common.update import Update
from pyarr._sync.utils.http import RequestHandler

T = TypeVar("T", bound="BaseArrClient")


class BaseArrClient:
    """Base class for all Arr clients."""

    def __init__(
        self,
        host: str,
        api_key: str,
        port: int,
        tls: bool = True,
        base_path: str = "",
        request_timeout: int | None = None,
        api_ver: str | None = None,
    ):
        """Initializes the client with the provided host, API key, and optional parameters.

        Args:
            host (str): The host to connect to.
            api_key (str): The API key for authentication.
            port (int): The port to connect to.
            tls (bool, optional): Whether to use TLS. Defaults to True.
            base_path (str, optional): The base path for the API. Defaults to "".
            request_timeout (int | None, optional): The timeout for requests. Defaults to None.
            api_ver (str | None, optional): The API version to use. Defaults to None, automatically detected.
        """
        self.http_utils = RequestHandler(
            host,
            api_key,
            port=port,
            tls=tls,
            base_path=base_path,
            request_timeout=request_timeout,
            api_ver=api_ver,
        )
        self.history = History(self.http_utils)
        self.backup = Backup(self.http_utils)
        self.system = System(self.http_utils)
        self.tag = Tag(self.http_utils)
        self.blocklist = Blocklist(self.http_utils)
        self.calendar = Calendar(self.http_utils)
        self.root_folder = RootFolder(self.http_utils)
        self.update = Update(self.http_utils)
        self.metadata = Metadata(self.http_utils)
        self.log = Log(self.http_utils)
        self.indexer = Indexer(self.http_utils)
        self.download_client = DownloadClient(self.http_utils)
        self.import_list = ImportList(self.http_utils)
        self.notification = Notification(self.http_utils)
        self.quality_profile = QualityProfile(self.http_utils)
        self.quality_definition = QualityDefinition(self.http_utils)
        self.queue = Queue(self.http_utils)
        self.remote_path_mapping = RemotePathMapping(self.http_utils)
        self.command = Command(self.http_utils)

    def __enter__(self: T) -> T:
        """Enter the runtime context related to this object.

        Returns:
            T: The client instance.
        """
        # Initialize resources if needed
        self.http_utils.__enter__()
        return self

    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        """Exit the runtime context related to this object.

        Args:
            exc_type (Any): The exception type.
            exc_value (Any): The exception value.
            traceback (Any): The traceback.
        """
        # Clean up resources
        self.http_utils.__exit__(exc_type, exc_value, traceback)
