# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.common.indexer import Indexer as CommonIndexer
from pyarr.types import JsonArray, JsonObject


class Indexer(CommonIndexer):
    """Indexer actions for Prowlarr."""

    def get_stats(self) -> JsonObject:
        """Gets indexer stats.

        Returns:
            JsonObject: Dictionary with indexer stats.
        """
        return self._get("indexerstats")

    def get_status(self) -> JsonArray:
        """Gets indexer status.

        Returns:
            JsonArray: List of dictionaries with indexer status.
        """
        return self._get("indexerstatus")
