# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.common.base import CommonActions
from pyarr.types import JsonArray, JsonObject


class Accounts(CommonActions):
    """Account actions for Dispatcharr."""

    def get_api_keys(self) -> JsonObject:
        """Retrieve API keys.

        Returns:
            JsonObject: The response data.
        """
        return self._get("accounts/api-keys/")

    def generate_api_key(self) -> JsonObject:
        """Generate a new API key.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("accounts/api-keys/generate/", method="POST")
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'accounts/api-keys/generate/' endpoint")

    def revoke_api_key(self) -> JsonObject:
        """Revoke an API key.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("accounts/api-keys/revoke/", method="POST")
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'accounts/api-keys/revoke/' endpoint")

    def login(self, data: JsonObject) -> JsonObject:
        """Authenticate and log in a user.

        Args:
            data (JsonObject): Login request data.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("accounts/auth/login/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'accounts/auth/login/' endpoint")

    def logout(self) -> JsonObject:
        """Log out the current user.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("accounts/auth/logout/", method="POST")
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'accounts/auth/logout/' endpoint")

    def get_groups(self, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve a list of groups or a specific group by ID.

        Args:
            item_id (int | None, optional): ID of the group to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get("accounts/groups/", item_id=item_id)

    def add_group(self, data: JsonObject) -> JsonObject:
        """Create a new group.

        Args:
            data (JsonObject): Group data.

        Returns:
            JsonObject: Added group details.
        """
        response = self.handler.request("accounts/groups/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'accounts/groups/' endpoint")

    def update_group(self, item_id: int, data: JsonObject) -> JsonObject:
        """Update a group.

        Args:
            item_id (int): Group ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated group details.
        """
        response = self.handler.request(f"accounts/groups/{item_id}/", method="PUT", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'accounts/groups/{item_id}/' endpoint")

    def partial_update_group(self, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update a group.

        Args:
            item_id (int): Group ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated group details.
        """
        response = self.handler.request(f"accounts/groups/{item_id}/", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'accounts/groups/{item_id}/' endpoint")

    def delete_group(self, item_id: int) -> None:
        """Delete a group.

        Args:
            item_id (int): Group ID.
        """
        self._delete("accounts/groups/", item_id=item_id)

    def get_permissions(self) -> JsonArray:
        """Retrieve a list of all permissions.

        Returns:
            JsonArray: The response data.
        """
        return self._get("accounts/permissions/")

    def create_token(self, data: JsonObject) -> JsonObject:
        """Takes a set of user credentials and returns an access and refresh JSON web token pair.

        Args:
            data (JsonObject): Token obtain pair data.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("accounts/token/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'accounts/token/' endpoint")

    def refresh_token(self, data: JsonObject) -> JsonObject:
        """Takes a refresh type JSON web token and returns an access type JSON web token.

        Args:
            data (JsonObject): Token refresh data.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("accounts/token/refresh/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'accounts/token/refresh/' endpoint")

    def get_users(self, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve a list of users or a specific user by ID.

        Args:
            item_id (int | None, optional): ID of the user to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get("accounts/users/", item_id=item_id)

    def add_user(self, data: JsonObject) -> JsonObject:
        """Create a new user.

        Args:
            data (JsonObject): User data.

        Returns:
            JsonObject: Added user details.
        """
        response = self.handler.request("accounts/users/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'accounts/users/' endpoint")

    def update_user(self, item_id: int, data: JsonObject) -> JsonObject:
        """Update a user.

        Args:
            item_id (int): User ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated user details.
        """
        response = self.handler.request(f"accounts/users/{item_id}/", method="PUT", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'accounts/users/{item_id}/' endpoint")

    def partial_update_user(self, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update a user.

        Args:
            item_id (int): User ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated user details.
        """
        response = self.handler.request(f"accounts/users/{item_id}/", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'accounts/users/{item_id}/' endpoint")

    def delete_user(self, item_id: int) -> None:
        """Delete a user.

        Args:
            item_id (int): User ID.
        """
        self._delete("accounts/users/", item_id=item_id)

    def get_me(self) -> JsonObject:
        """Get active user information.

        Returns:
            JsonObject: The response data.
        """
        return self._get("accounts/users/me/")

    def partial_update_me(self, data: JsonObject) -> JsonObject:
        """Update active user information.

        Args:
            data (JsonObject): Patched user data.

        Returns:
            JsonObject: Updated user details.
        """
        response = self.handler.request("accounts/users/me/", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'accounts/users/me/' endpoint")
