# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.common.base import CommonActions
from pyarr.types import JsonArray, JsonObject


class Backups(CommonActions):
    """Backup actions for Dispatcharr."""

    def get(self) -> JsonArray:
        """List all available backup files.

        Returns:
            JsonArray: The response data.
        """
        return self._get("backups/")

    def delete(self, filename: str) -> None:
        """Delete a backup file.

        Args:
            filename (str): The name of the backup file to delete.
        """
        self.handler.request(f"backups/{filename}/delete/", method="DELETE")

    def download(self, filename: str, token: str | None = None) -> JsonObject:
        """Download a backup file.

        Args:
            filename (str): The name of the backup file to download.
            token (str | None, optional): Download token. Defaults to None.

        Returns:
            JsonObject: The response data.
        """
        params = {}
        if token:
            params["download_token"] = token
        return self._get(f"backups/{filename}/download/", params=params)

    def get_download_token(self, filename: str) -> JsonObject:
        """Get a signed token for downloading a backup file.

        Args:
            filename (str): The name of the backup file.

        Returns:
            JsonObject: The response data.
        """
        return self._get(f"backups/{filename}/download-token/")

    def restore(self, filename: str) -> JsonObject:
        """Restore from a backup file.

        Args:
            filename (str): The name of the backup file to restore.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request(f"backups/{filename}/restore/", method="POST")
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'backups/{filename}/restore/' endpoint")

    def create(self) -> JsonObject:
        """Create a new backup.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("backups/create/", method="POST")
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'backups/create/' endpoint")

    def get_schedule(self) -> JsonObject:
        """Get backup schedule settings.

        Returns:
            JsonObject: The response data.
        """
        return self._get("backups/schedule/")

    def update_schedule(self, data: JsonObject) -> JsonObject:
        """Update backup schedule settings.

        Args:
            data (JsonObject): Schedule settings.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("backups/schedule/update/", method="PUT", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'backups/schedule/update/' endpoint")

    def get_status(self, task_id: str, token: str | None = None) -> JsonObject:
        """Check the status of a backup/restore task.

        Args:
            task_id (str): Task ID.
            token (str | None, optional): Task token. Defaults to None.

        Returns:
            JsonObject: The response data.
        """
        params = {}
        if token:
            params["task_token"] = token
        return self._get(f"backups/status/{task_id}/", params=params)

    def upload(self, data: JsonObject) -> JsonObject:
        """Upload a backup file for restoration.

        Args:
            data (JsonObject): Backup file data.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("backups/upload/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'backups/upload/' endpoint")
