# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.common.base import CommonActions
from pyarr.types import JsonArray, JsonObject


class ChannelProfiles(CommonActions):
    """Channel profile actions for Dispatcharr."""

    def get(self, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve channel profiles.

        Args:
            item_id (int | None, optional): ID of the profile to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get("channels/profiles", item_id=item_id)

    def add(self, data: JsonObject) -> JsonObject:
        """Create a new channel profile.

        Args:
            data (JsonObject): Profile data.

        Returns:
            JsonObject: Added profile details.
        """
        response = self.handler.request("channels/profiles", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'channels/profiles' endpoint")

    def update(self, item_id: int, data: JsonObject) -> JsonObject:
        """Update a channel profile.

        Args:
            item_id (int): Profile ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated profile details.
        """
        response = self.handler.request(f"channels/profiles/{item_id}", method="PUT", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'channels/profiles/{item_id}' endpoint")

    def partial_update(self, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update a channel profile.

        Args:
            item_id (int): Profile ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated profile details.
        """
        response = self.handler.request(f"channels/profiles/{item_id}", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'channels/profiles/{item_id}' endpoint")

    def delete(self, item_id: int) -> None:
        """Delete a channel profile.

        Args:
            item_id (int): Profile ID.
        """
        self._delete("channels/profiles", item_id=item_id)

    def duplicate(self, item_id: int) -> JsonObject:
        """Duplicate a channel profile.

        Args:
            item_id (int): Profile ID.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request(f"channels/profiles/{item_id}/duplicate", method="POST")
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'channels/profiles/{item_id}/duplicate' endpoint")

    def partial_update_channels(self, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update channels in a profile.

        Args:
            item_id (int): Profile ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated profile details.
        """
        response = self.handler.request(f"channels/profiles/{item_id}/channels", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'channels/profiles/{item_id}/channels' endpoint")

    def bulk_update_channels(self, item_id: int, data: JsonObject) -> JsonObject:
        """Bulk update channels in a profile.

        Args:
            item_id (int): Profile ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated profile details.
        """
        response = self.handler.request(
            f"channels/profiles/{item_id}/channels/bulk-update",
            method="PATCH",
            json_data=data,
        )
        if isinstance(response, dict):
            return response
        raise ValueError(
            f"Expected a dictionary response from the 'channels/profiles/{item_id}/channels/bulk-update' endpoint"
        )
