# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.common.base import CommonActions
from pyarr.types import JsonArray, JsonObject


class Epg(CommonActions):
    """EPG actions for Dispatcharr."""

    def get_current_programs(self, data: JsonObject) -> JsonArray | JsonObject:
        """Retrieve current programs.

        Args:
            data (JsonObject): Request data.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        response = self.handler.request("epg/current-programs/", method="POST", json_data=data)
        return response

    def get_epg_data(self, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve EPG data.

        Args:
            item_id (int | None, optional): ID of the EPG data to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get("epg/epgdata/", item_id=item_id)

    def get_grid(self) -> JsonArray:
        """Retrieve EPG grid.

        Returns:
            JsonArray: The response data.
        """
        return self._get("epg/grid/")

    def import_epg(self, data: JsonObject) -> JsonObject:
        """Import EPG data.

        Args:
            data (JsonObject): Import request data.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("epg/import/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'epg/import/' endpoint")

    def get_programs(self, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve EPG programs.

        Args:
            item_id (int | None, optional): ID of the program to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get("epg/programs/", item_id=item_id)

    def add_program(self, data: JsonObject) -> JsonObject:
        """Create a new EPG program.

        Args:
            data (JsonObject): Program data.

        Returns:
            JsonObject: Added program details.
        """
        response = self.handler.request("epg/programs/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'epg/programs/' endpoint")

    def update_program(self, item_id: int, data: JsonObject) -> JsonObject:
        """Update an EPG program.

        Args:
            item_id (int): Program ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated program details.
        """
        response = self.handler.request(f"epg/programs/{item_id}/", method="PUT", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'epg/programs/{item_id}/' endpoint")

    def partial_update_program(self, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update an EPG program.

        Args:
            item_id (int): Program ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated program details.
        """
        response = self.handler.request(f"epg/programs/{item_id}/", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'epg/programs/{item_id}/' endpoint")

    def delete_program(self, item_id: int) -> None:
        """Delete an EPG program.

        Args:
            item_id (int): Program ID.
        """
        self._delete("epg/programs/", item_id=item_id)

    def get_sources(self, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve EPG sources.

        Args:
            item_id (int | None, optional): ID of the source to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get("epg/sources/", item_id=item_id)

    def add_source(self, data: JsonObject) -> JsonObject:
        """Create a new EPG source.

        Args:
            data (JsonObject): Source data.

        Returns:
            JsonObject: Added source details.
        """
        response = self.handler.request("epg/sources/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'epg/sources/' endpoint")

    def update_source(self, item_id: int, data: JsonObject) -> JsonObject:
        """Update an EPG source.

        Args:
            item_id (int): Source ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated source details.
        """
        response = self.handler.request(f"epg/sources/{item_id}/", method="PUT", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'epg/sources/{item_id}/' endpoint")

    def partial_update_source(self, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update an EPG source.

        Args:
            item_id (int): Source ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated source details.
        """
        response = self.handler.request(f"epg/sources/{item_id}/", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'epg/sources/{item_id}/' endpoint")

    def delete_source(self, item_id: int) -> None:
        """Delete an EPG source.

        Args:
            item_id (int): Source ID.
        """
        self._delete("epg/sources/", item_id=item_id)

    def upload_source(self, data: JsonObject) -> JsonObject:
        """Upload an EPG source.

        Args:
            data (JsonObject): Source file data.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("epg/sources/upload/", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'epg/sources/upload/' endpoint")
