# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.common.base import CommonActions
from pyarr.types import JsonArray, JsonObject


class M3u(CommonActions):
    """M3U actions for Dispatcharr."""

    def get_accounts(self, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve M3U accounts.

        Args:
            item_id (int | None, optional): ID of the account to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get("m3u/accounts", item_id=item_id)

    def add_account(self, data: JsonObject) -> JsonObject:
        """Create a new M3U account.

        Args:
            data (JsonObject): Account data.

        Returns:
            JsonObject: Added account details.
        """
        response = self.handler.request("m3u/accounts", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'm3u/accounts' endpoint")

    def update_account(self, item_id: int, data: JsonObject) -> JsonObject:
        """Update an M3U account.

        Args:
            item_id (int): Account ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated account details.
        """
        response = self.handler.request(f"m3u/accounts/{item_id}", method="PUT", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'm3u/accounts/{item_id}' endpoint")

    def partial_update_account(self, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update an M3U account.

        Args:
            item_id (int): Account ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated account details.
        """
        response = self.handler.request(f"m3u/accounts/{item_id}", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'm3u/accounts/{item_id}' endpoint")

    def delete_account(self, item_id: int) -> None:
        """Delete an M3U account.

        Args:
            item_id (int): Account ID.
        """
        self._delete("m3u/accounts", item_id=item_id)

    def partial_update_account_group_settings(self, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update M3U account group settings.

        Args:
            item_id (int): Account ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated settings.
        """
        response = self.handler.request(f"m3u/accounts/{item_id}/group-settings", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'm3u/accounts/{item_id}/group-settings' endpoint")

    def refresh_account_vod(self, item_id: int) -> JsonObject:
        """Refresh VOD for an M3U account.

        Args:
            item_id (int): Account ID.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request(f"m3u/accounts/{item_id}/refresh-vod", method="POST")
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'm3u/accounts/{item_id}/refresh-vod' endpoint")

    def get_account_filters(self, account_id: int, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve M3U account filters.

        Args:
            account_id (int): Account ID.
            item_id (int | None, optional): ID of the filter to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get(f"m3u/accounts/{account_id}/filters", item_id=item_id)

    def add_account_filter(self, account_id: int, data: JsonObject) -> JsonObject:
        """Create a new M3U account filter.

        Args:
            account_id (int): Account ID.
            data (JsonObject): Filter data.

        Returns:
            JsonObject: Added filter details.
        """
        response = self.handler.request(f"m3u/accounts/{account_id}/filters", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'm3u/accounts/{account_id}/filters' endpoint")

    def update_account_filter(self, account_id: int, item_id: int, data: JsonObject) -> JsonObject:
        """Update an M3U account filter.

        Args:
            account_id (int): Account ID.
            item_id (int): Filter ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated filter details.
        """
        response = self.handler.request(
            f"m3u/accounts/{account_id}/filters/{item_id}",
            method="PUT",
            json_data=data,
        )
        if isinstance(response, dict):
            return response
        raise ValueError(
            f"Expected a dictionary response from the 'm3u/accounts/{account_id}/filters/{item_id}' endpoint"
        )

    def partial_update_account_filter(self, account_id: int, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update an M3U account filter.

        Args:
            account_id (int): Account ID.
            item_id (int): Filter ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated filter details.
        """
        response = self.handler.request(
            f"m3u/accounts/{account_id}/filters/{item_id}",
            method="PATCH",
            json_data=data,
        )
        if isinstance(response, dict):
            return response
        raise ValueError(
            f"Expected a dictionary response from the 'm3u/accounts/{account_id}/filters/{item_id}' endpoint"
        )

    def delete_account_filter(self, account_id: int, item_id: int) -> None:
        """Delete an M3U account filter.

        Args:
            account_id (int): Account ID.
            item_id (int): Filter ID.
        """
        self.handler.request(f"m3u/accounts/{account_id}/filters/{item_id}", method="DELETE")

    def get_account_profiles(self, account_id: int, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve M3U account profiles.

        Args:
            account_id (int): Account ID.
            item_id (int | None, optional): ID of the profile to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get(f"m3u/accounts/{account_id}/profiles", item_id=item_id)

    def add_account_profile(self, account_id: int, data: JsonObject) -> JsonObject:
        """Create a new M3U account profile.

        Args:
            account_id (int): Account ID.
            data (JsonObject): Profile data.

        Returns:
            JsonObject: Added profile details.
        """
        response = self.handler.request(f"m3u/accounts/{account_id}/profiles", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'm3u/accounts/{account_id}/profiles' endpoint")

    def update_account_profile(self, account_id: int, item_id: int, data: JsonObject) -> JsonObject:
        """Update an M3U account profile.

        Args:
            account_id (int): Account ID.
            item_id (int): Profile ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated profile details.
        """
        response = self.handler.request(
            f"m3u/accounts/{account_id}/profiles/{item_id}",
            method="PUT",
            json_data=data,
        )
        if isinstance(response, dict):
            return response
        raise ValueError(
            f"Expected a dictionary response from the 'm3u/accounts/{account_id}/profiles/{item_id}' endpoint"
        )

    def partial_update_account_profile(self, account_id: int, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update an M3U account profile.

        Args:
            account_id (int): Account ID.
            item_id (int): Profile ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated profile details.
        """
        response = self.handler.request(
            f"m3u/accounts/{account_id}/profiles/{item_id}",
            method="PATCH",
            json_data=data,
        )
        if isinstance(response, dict):
            return response
        raise ValueError(
            f"Expected a dictionary response from the 'm3u/accounts/{account_id}/profiles/{item_id}' endpoint"
        )

    def delete_account_profile(self, account_id: int, item_id: int) -> None:
        """Delete an M3U account profile.

        Args:
            account_id (int): Account ID.
            item_id (int): Profile ID.
        """
        self.handler.request(f"m3u/accounts/{account_id}/profiles/{item_id}", method="DELETE")

    def refresh(self, data: JsonObject) -> JsonObject:
        """Refresh M3U data.

        Args:
            data (JsonObject): Refresh request data.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("m3u/refresh", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'm3u/refresh' endpoint")

    def refresh_account_info(self, data: JsonObject) -> JsonObject:
        """Refresh M3U account info.

        Args:
            data (JsonObject): Refresh request data.

        Returns:
            JsonObject: The response data.
        """
        response = self.handler.request("m3u/refresh-account-info", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'm3u/refresh-account-info' endpoint")

    def get_server_groups(self, item_id: int | None = None) -> JsonArray | JsonObject:
        """Retrieve M3U server groups.

        Args:
            item_id (int | None, optional): ID of the group to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get("m3u/server-groups", item_id=item_id)

    def add_server_group(self, data: JsonObject) -> JsonObject:
        """Create a new M3U server group.

        Args:
            data (JsonObject): Group data.

        Returns:
            JsonObject: Added group details.
        """
        response = self.handler.request("m3u/server-groups", method="POST", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'm3u/server-groups' endpoint")

    def update_server_group(self, item_id: int, data: JsonObject) -> JsonObject:
        """Update an M3U server group.

        Args:
            item_id (int): Group ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated group details.
        """
        response = self.handler.request(f"m3u/server-groups/{item_id}", method="PUT", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'm3u/server-groups/{item_id}' endpoint")

    def partial_update_server_group(self, item_id: int, data: JsonObject) -> JsonObject:
        """Partially update an M3U server group.

        Args:
            item_id (int): Group ID.
            data (JsonObject): Updated configuration.

        Returns:
            JsonObject: Updated group details.
        """
        response = self.handler.request(f"m3u/server-groups/{item_id}", method="PATCH", json_data=data)
        if isinstance(response, dict):
            return response
        raise ValueError(f"Expected a dictionary response from the 'm3u/server-groups/{item_id}' endpoint")

    def delete_server_group(self, item_id: int) -> None:
        """Delete an M3U server group.

        Args:
            item_id (int): Group ID.
        """
        self._delete("m3u/server-groups", item_id=item_id)
