# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.utils.http import RequestHandler


class Config:
    """Config actions for Readarr."""

    def __init__(self, handler: RequestHandler):
        """Initializes the config actions with the provided request handler.

        Args:
            handler (RequestHandler): The request handler to use for API requests.
        """
        self.handler = handler
