import os
import pathlib

import unasync


def fix_sync_code(filepath):
    content = pathlib.Path(filepath).read_text()
    if not content.startswith('# """'):
        # Add DO NOT EDIT header
        header = (
            '# """\n'
            "# This file is automatically generated from the async version.\n"
            "# Do not edit this file directly.\n"
            '# """\n\n'
        )
        content = header + content

    # unasync sometimes misses things or we need custom replacements

    new_content = content.replace("pyarr._async", "pyarr._sync")
    new_content = new_content.replace("httpx.AsyncClient", "httpx.Client")
    new_content = new_content.replace("httpx.SyncClient", "httpx.Client")
    new_content = new_content.replace("self.session.aclose()", "self.session.close()")
    new_content = new_content.replace("await self.session.aclose()", "self.session.close()")

    if new_content != content:
        with open(filepath, "w") as f:
            f.write(new_content)


def main():
    rules = [
        unasync.Rule(
            fromdir="/src/pyarr/_async/",
            todir="/src/pyarr/_sync/",
            additional_replacements={
                "httpx.AsyncClient": "httpx.Client",
                "pyarr._async": "pyarr._sync",
                "aclose": "close",
            },
        )
    ]

    filepaths = []
    async_dir = os.path.join(os.path.dirname(__file__), "..", "src", "pyarr", "_async")
    for root, _, files in os.walk(async_dir):
        filepaths.extend(os.path.join(root, file) for file in files if file.endswith(".py"))
    unasync.unasync_files(filepaths, rules)

    # Post-process sync files to fix any remaining issues
    sync_dir = os.path.join(os.path.dirname(__file__), "..", "src", "pyarr", "_sync")
    for root, _, files in os.walk(sync_dir):
        for file in files:
            if file.endswith(".py"):
                fix_sync_code(os.path.join(root, file))


if __name__ == "__main__":
    main()
