# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.common.base import CommonActions
from pyarr.types import JsonArray


class ManualImport(CommonActions):
    """Manual import actions for Sonarr."""

    def get(
        self,
        folder: str,
        download_id: str | None = None,
        series_id: int | None = None,
        filter_existing_files: bool = True,
        replace_existing_files: bool = True,
    ) -> JsonArray:
        """Gets a manual import list.

        Args:
            folder (str): Folder name.
            download_id (str | None, optional): Download ID. Defaults to None.
            series_id (int | None, optional): Series Database ID. Defaults to None.
            filter_existing_files (bool, optional): Filter files. Defaults to True.
            replace_existing_files (bool, optional): Replace files. Defaults to True.

        Returns:
            JsonArray: List of dictionaries with items.
        """
        params: dict[str, str | int | bool] = {"folder": folder}
        if download_id:
            params["downloadId"] = download_id
        if series_id:
            params["seriesId"] = series_id

        params["filterExistingFiles"] = filter_existing_files
        params["replaceExistingFiles"] = replace_existing_files

        response = self.handler.request("manualimport", params=params)
        if isinstance(response, list):
            return response
        raise ValueError("Expected a list response from the 'manualimport' endpoint")

    def update(self, data: JsonArray) -> JsonArray:
        """Process the given manual import items.

        Args:
            data (JsonArray): List of manual import items, as returned by get().

        Returns:
            JsonArray: List of dictionaries with the processed items.
        """
        response = self.handler.request("manualimport", method="POST", json_data=data)
        if isinstance(response, list):
            return response
        raise ValueError("Expected a list response from the 'manualimport' endpoint")
