# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.common.base import CommonActions
from pyarr.types import JsonObject


class Providers(CommonActions):
    """Subtitle provider actions for Bazarr."""

    def get(self) -> JsonObject:
        """Returns the subtitle providers Bazarr knows about.

        Returns:
            JsonObject: Dictionary with a ``data`` list of providers.
        """
        response = self.handler.request("providers")
        if isinstance(response, dict):
            return response
        raise ValueError("Expected a dictionary response from the 'providers' endpoint")
