# """
# This file is automatically generated from the async version.
# Do not edit this file directly.
# """

from pyarr._sync.common.base import CommonActions
from pyarr.types import JsonArray, JsonObject


class RemotePathMapping(CommonActions):
    """Remote path mapping actions for Arr clients."""

    def get(self, item_id: int | None = None) -> JsonArray | JsonObject:
        """Returns the list of remote path mappings or a specific mapping by ID.

        Args:
            item_id (int | None, optional): ID of the mapping to return. Defaults to None.

        Returns:
            JsonArray | JsonObject: The response data.
        """
        return self._get("remotepathmapping", item_id=item_id)
