name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # Skip on release-please PRs
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code-quality:
    name: 📊 Check code quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run containers
        run: docker compose -f .ci/docker-compose.yml up -d

      - name: Add hosts
        run: |
          sudo echo "127.0.0.1 sonarr readarr radarr lidarr prowlarr bazarr whisparr dispatcharr deluge jackett" | sudo tee -a /etc/hosts

      - name: sleep 30s for containers to start-up
        run: sleep 30s
        shell: bash

      - name: check ports are mapped
        run: docker ps

      - name: check one of the containers is up
        run: curl http://radarr:7878

      - name: 🧪 Check tests are passing
        run: |
          uv run nox -s tests
